version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mynewpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: postgresql://todo_db_12ho_user:YvunnJZ3Zrh1wu1zem1tnkJBT5iAEvAo@dpg-d0j3006mcj7s73aj9g30-a.oregon-postgres.render.com/todo_db_12ho
      SPRING_DATASOURCE_USERNAME: todo_db_12ho_user
      SPRING_DATASOURCE_PASSWORD: YvunnJZ3Zrh1wu1zem1tnkJBT5iAEvAo


volumes:
  pgdata
