version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0n00em3jp1c738oaj70-a.oregon-postgres.render.com/tododb_4k7h
      SPRING_DATASOURCE_USERNAME: todouser
      SPRING_DATASOURCE_PASSWORD: PUIPDX0IiwJCLr5FDmQJFy2RfmLLiWHZ


volumes:
  pgdata:
